Update README.md
ferreiratiago/paddy pull request #12
Opened 2022-08-30 22:21 UTC by marcelosousa

This pull request makes a simple change to the README.md

2022-08-30 22:48 UTC, marcelosousa commented
I can comment the pull request

2022-08-30 22:48 UTC, marcelosousa commented
But I can't add a label to it

2022-08-31 08:25 UTC, ferreiratiago approved these changes

2022-08-31 08:25 UTC, ferreiratiago commented on README.md
> +This project is used to play with the [Reviewpad Action](https://reviewpad.com) :raised_hands:
Good

2022-08-31 08:28 UTC, marcelosousa commented
/reviewpad run

2022-08-31 08:30 UTC, ferreiratiago requested changes

2022-08-31 08:30 UTC, ferreiratiago commented on README.md
> +This project is used to play with the [Reviewpad Action](https://reviewpad.com) :raised_hands:
Good x2

2022-08-31 08:33 UTC, ferreiratiago requested changes

2022-08-31 08:33 UTC, ferreiratiago commented on README.md
> +This project is used to play with the [Reviewpad Action](https://reviewpad.com) :raised_hands:
Try

2022-10-29 13:46 UTC, closed without merging