update file
ferreiratiago/paddy pull request #6
Opened 2022-08-08 16:52 UTC by ferreiratiago

2022-08-08 16:55 UTC, padawancat requested changes

2022-08-08 16:55 UTC, padawancat commented on src/file.go
> +	fmt.Println("Hello, world x1!")
Why this?

2022-08-08 17:12 UTC, padawancat commented on src/file.go
> +	fmt.Println("Hello, world x1!")
Hum.

2022-08-08 17:16 UTC, padawancat commented on src/file.go
> +	fmt.Println("Hello, world x1!")
Hello

2022-08-08 17:17 UTC, padawancat commented
General comment.

2022-08-08 17:20 UTC, padawancat commented
General comment 2.

2022-08-09 09:35 UTC, padawancat approved these changes

2022-08-09 10:45 UTC, padawancat requested changes

2022-08-09 10:45 UTC, padawancat commented on src/file.go
> +	fmt.Println("Hello, world x3!")
Why this?

2022-08-09 11:06 UTC, ferreiratiago commented on src/file.go
> +	fmt.Println("Hello, world x3!")
/reviewpad resolve

2022-08-09 14:39 UTC, ferreiratiago commented
/reviewpad run

2022-08-09 14:44 UTC, ferreiratiago commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

:scroll: **Executed actions**
```yaml
$addLabel("waiting-review")
```

2022-08-10 14:03 UTC, ferreiratiago commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

:scroll: **Executed actions**
```yaml
$rebase()
```

2022-08-11 09:58 UTC, ferreiratiago commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:bangbang: Errors**
* **Unconventional commit detected**: 'update workflow' (8b856e8d09c11c8f561af6fdf3c9f4e100ede0b9)
* **Unconventional commit detected**: 'update file' (4539451a2b7c294753ecc39a39f1426d310a7b06)
* **Unconventional commit detected**: 'update file' (2b5022f0c40ad6573c2e322d5ddf78f720a836f0)
* **Unconventional commit detected**: 'update file' (0b837d3457492d4d77ea75426a1900ba233466b8)
* **Unconventional commit detected**: 'add changes' (8b72055b676c5bcf8dbc5aaaf4611b46dfe48483)

2022-08-18 13:50 UTC, ferreiratiago commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

:scroll: **Executed actions**
```yaml
$rebase()
```

2022-09-05 20:58 UTC, ferreiratiago commented
/reviewpad merge squash

2022-10-29 13:46 UTC, closed without merging